description: "Click issue sidebar weight edit button"
category: default
action: click_edit_button
label_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: product_planning
milestone: "12.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/14944
distributions:
- ee
tiers:
- premium
- ultimate
additional_properties:
  property:
    description: "`weight`"
